#!/usr/bin/env python
# Copyright (c) 2009 Alexandre Quessy, Arjan Scherpenisse
# See LICENSE for details.
"""
Sends OSC messages using txosc
"""
from twisted.internet import reactor
from twisted.internet import defer
from txosc import osc
import os
import sys


# Only to set PYTHONPATH
if __name__ == "__main__":
    d = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, d)
    import bideew
    from bideew import *


@defer.inlineCallbacks
def run():
    bideew.VERBOSE = True
    sender = MapMapController()
    yield sender.send(osc.Message("/hello", 1, 3.123, "world"))
    yield later(1.0) # wait 1 second
    yield sender.send(osc.Message("/hello", 2, 3.123, "world"))
    reactor.stop()


if __name__ == "__main__":
    def _later():
        run()

    reactor.callLater(0.001, _later)
    reactor.run()
